### ISSUE TITLE
[QUESTION] Why Does AutoTorch Places A Torch In Overworld Even Though It Is Daytime?

### ISSUE THREAD

**Issue by Heisenborgar** [necessary129/minecraft-autotorch#3]
Refer to the picture here:
![2021-06-21_09 07 32](https://user-images.githubusercontent.com/64238265/122694516-25f64a00-d270-11eb-9287-46c5994af127.png)

Any explanation? Great mod btw!

**Comment by necessary129** [comment]
Hello,

That was a deliberate decision I made to use only the `BLOCK` light level and not consider Skylight or internal Skylight. It was because my main objective for the mod was to help me in spawn proofing places, and placing on blocks which may have a internal skylight which does not allow spawning at the moment, but will allow spawning at night was considered a feature. As that will stop mob spawning entirely. (And I do not have to wait for it to be night to place torches around my house)

I guess if it is needed, I could make it configurable to check only Blocklight level or check both the internal skylight and blocklight level.

**Comment by Heisenborgar** [comment]
Oh, I see, thank you for answering my question!
